-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT * PRICE) AS SALES
FROM PRODUCT P
LEFT JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE SALES_AMOUNT != 0
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC

# SELECT *
# FROM PRODUCT P
# LEFT JOIN OFFLINE_SALE O
# ON P.PRODUCT_ID = O.PRODUCT_ID

# PRODUCT_ID, PRODUCT_CODE, PRICE는 각각 
# 상품 ID, 상품코드, 판매가