-- 코드를 입력하세요
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE JOINED LIKE '2021%' AND AGE >= 20 AND AGE <= 29

# SELECT COUNT(USER_ID) AS USERS
# FROM USER_INFO 
# WHERE JOINED LIKE '2021%'
# GROUP BY AGE
# HAVING AGE >= 20 AND AGE <= 29;

# USER_ID, GENDER, AGE, JOINED는 각각 
# 회원 ID, 성별, 나이, 가입일을