-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT P
LEFT JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05%'
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID

# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
# FROM FOOD_PRODUCT P
# LEFT JOIN FOOD_ORDER O
# ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE O.PRODUCE_DATE LIKE '2022-05%'
# ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID

# PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE 
# 식품 ID, 식품 이름, 식품코드, 식품분류, 식품 가격

# ORDER_ID, PRODUCT_ID, AMOUNT, PRODUCE_DATE, IN_DATE, OUT_DATE, FACTORY_ID, WAREHOUSE_ID
# 주문 ID, 제품 ID, 주문량, 생산일자, 입고일자, 출고일자, 공장 ID, 창고 ID