-- 코드를 입력하세요
# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
# FROM MEMBER_PROFILE M
# LEFT JOIN REST_REVIEW R
# ON M.MEMBER_ID = R.MEMBER_ID
# GROUP BY R.REVIEW_ID
# ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
LEFT JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_NAME = (
    SELECT M2.MEMBER_NAME
    FROM MEMBER_PROFILE M2
    LEFT JOIN REST_REVIEW R2 ON M2.MEMBER_ID = R2.MEMBER_ID
    GROUP BY M2.MEMBER_NAME
    ORDER BY COUNT(R2.REVIEW_ID) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT


# MEMBER_PROFILE 고객 정보, REST_REVIEW 리뷰 정보

# MEMBER_ID, MEMBER_NAME,   TLNO,          GENDER,   DATE_OF_BIRTH 는 
# 회원 ID,    회원 이름,      회원 연락처,     성별,     생년월일을 의미

# REVIEW_ID, REST_ID,  MEMBER_ID,  REVIEW_SCORE,  REVIEW_TEXT,  REVIEW_DATE 는 각각 
# 리뷰 ID,    식당 ID,  회원 ID,     점수,           리뷰 텍스트,   리뷰 작성일

# 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일이 출력되도록 작성
# 리뷰 작성일을 기준으로 오름차순, 리뷰 작성일이 같다면 리뷰 텍스트를 기준으로 오름차순 정렬